trigger:
- master

pool:
  name: MoneyTransfer

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - checkout: self
      persistCredentials: true  # Persist the GitHub connection using Personal Access Token

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

- stage: Deliver
  displayName: 'Deliver Stage'
  dependsOn: Build
  jobs:
  - job: DeliverJob
    displayName: 'Deliver Job'
    steps:
    - task: PublishPipelineArtifact@0
      displayName: 'Publish pipeline artifact'
      inputs:
        artifactName: 'MoneyTransferArtifact'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: DeployToDev
  displayName: 'Deploy to Dev Env Stage'
  dependsOn: Deliver
  jobs:
  - job: DeployToDevJob
    displayName: 'Deploy to Dev Env Job'
    steps:
    - script: echo "Skipping deployment to Dev environment"
      displayName: 'Mocked deployment'

- stage: DeployToQAT
  displayName: 'Deploy to QAT Env Stage'
  dependsOn: DeployToDev
  condition: false  # Mocked stage since QAT environment is not applicable
  jobs:
  - job: DeployToQATJob
    displayName: 'Deploy to QAT Env Job'
    steps:
    - script: echo "Skipping deployment to QAT environment"
      displayName: 'Mocked deployment'

- stage: DeployToStaging
  displayName: 'Deploy to Staging Env Stage'
  dependsOn: DeployToQAT
  condition: false  # Mocked stage since Staging environment is not applicable
  jobs:
  - job: DeployToStagingJob
    displayName: 'Deploy to Staging Env Job'
    steps:
    - script: echo "Skipping deployment to Staging environment"
      displayName: 'Mocked deployment'

- stage: DeployToProduction
  displayName: 'Deploy to Production Env Stage'
  dependsOn: DeployToStaging
  jobs:
  - job: DeployToProductionJob
    displayName: 'Deploy to Production Env Job'
    steps:
    - script: echo "Skipping deployment to Production environment"
      displayName: 'Mocked deployment'
