trigger:
- master

pool:
  name: MoneyTransfer

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Stage Job'
    steps:
    - checkout: self
      persistCredentials: true  # Persist the GitHub connection using Personal Access Token

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Your_Project_Key'
        cliProjectName: 'Your_Project_Name'
        cliSources: '.'
        extraProperties: '-X'


    - task: SonarQubeAnalyze@4

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
